name: Trigger auto deployment for django

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DJANGO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DJANGO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DJANGO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: djangoefranco2026.azurecr.io
          registryUsername: ${{ secrets.DJANGO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DJANGO_REGISTRY_PASSWORD }}
          containerAppName: django
          resourceGroup: RG-Django
          imageToBuild: djangoefranco2026.azurecr.io/django:${{ github.sha }}
